name: interest_me_mobile_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_tts: ^0.1.0
  font_awesome_flutter: ^8.0.1
 # css_colors: ^1.0.0
  flutter:
    sdk: flutter
  firebase_core: ^0.2.5
  firebase_auth: 0.6.2+1
  firebase_storage: 1.0.4
  firebase_messaging: ^2.1.0
  cloud_firestore: 0.8.2+3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^0.12.2+1
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  fluttertoast: ^2.0.9
  image_picker: ^0.4.10
  intl: ^0.15.7
  screen: ^0.0.4
  flutter_launcher_icons: "^0.6.1"
  html_unescape: ^1.0.1+2
  flutter_local_notifications: ^0.4.2
  flutter_youtube_extractor: ^0.0.8
  connectivity: ^0.3.2
  flutter_youtube: "^1.1.4"
  youtube_extractor: ^1.0.1
  transparent_image: ^0.1.0
  audioplayer: ^0.5.2
  audio_recorder: ^0.0.6  
  carousel_slider: ^1.1.0
  permission: ^0.1.1

dependency_overrides:
  flutter_cache_manager: ^0.2.0
  cached_network_image: ^0.5.0
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true 
  ios: "Example-Icon"
  image_path: "assets/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/click.mp3
  - assets/sent.mp3
  - assets/logo.png
  - assets/logo_anim.gif
  - assets/say2.gif
  - assets/chat.gif
  - assets/find.gif
  - assets/profile.gif
  - assets/stories.gif
  - assets/say_w.gif
  - assets/chat_w.gif
  - assets/find_w.gif
  - assets/profile_w.gif
  - assets/story_w.gif
  - assets/say1.jpg
  - assets/say2.jpg
  - assets/say3.jpg
  - assets/say4.jpg
  - assets/say5.jpg
  - assets/say6.jpg
  - assets/story5.jpg
  - assets/story1.jpg
  - assets/story2.jpg
  - assets/story3.jpg
  - assets/story4.jpg
  - assets/find1.jpg
  - assets/find2.jpg
  - assets/find3.jpg
  - assets/find4.jpg
  - assets/find5.jpg
  - assets/find6.jpg
  - assets/chat1.jpg
  - assets/chat2.jpg
  - assets/chat3.jpg
  - assets/profile1.jpg
  - assets/profile2.jpg
  - assets/profile3.jpg
  - assets/profile4.jpg
  - assets/profile5.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
